### ISSUE TITLE
Plaintext serialization

### ISSUE THREAD

**Issue by christopher-dG** [JuliaTesting/BrokenRecord.jl#2]
I used BSON when I first wrote this package because it was just way easier than anything else, but storing unreadable binary files in Git repos is annoying. It would be nice to support YAML and JSON.

**Comment by DilumAluthge** [comment]
It would also be nice to support some other binary serialization formats. The two I would like to use are:
1. JLD2.jl
2. JLSO.jl

**Comment by DilumAluthge** [comment]
Although, the more packages that you add, the more dependencies you'd have to add.

So maybe it's best to keep the list short.

**Comment by DilumAluthge** [comment]
I guess the question is: do you need both JSON and YAML?

You could offer one binary format (BSON) and one human readable format (JSON).

So then you'd only need to have two dependencies:
1. BSON.jl
2. JSON3.jl

**Comment by christopher-dG** [comment]
I don't really have a problem with having a few extra dependencies as long as they're just Julia code or BB-built binaries. And there's really only so many reasonable backends, so IMO it's fine to just cover most if not all of them at once.

**Comment by DilumAluthge** [comment]
Another question: do you want to let people pick which package to use for a single format?

E.g. if some users want to use JSON.jl but others want to use JSON3.jl, would you support only one? Or would you support both, and the user can select with `configure!`.

**Comment by christopher-dG** [comment]
The package used for serialization doesn't need to be visible to the user IMO, i.e. they shouldn't know nor care whether JSON or JSON3 is being used.

**Comment by DilumAluthge** [comment]
Just to confirm, you never need to serialized/deserialize a user defined type, right? You only serialize/deserialize types from the HTTP.jl package?

**Comment by christopher-dG** [comment]
Correct.
