### ISSUE TITLE
Filter response headers

### ISSUE THREAD

**Issue by fredrikekre** [JuliaTesting/BrokenRecord.jl#8]
I would like to filder out some incoming HTTP headers, but it seems like `ignore_headers` is only applied to outgoing headers right now.

**Comment by christopher-dG** [comment]
Seems reasonable, and easy to add.
I guess the only question is should we make `ignore_headers` filter both request and response headers, or have `ignore_request_headers` and `ignore_response_headers`? I am leaning towards the former, I can't see any situations where it would bite you.
I should be able to take care of this on Monday.
